#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     driveLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     armRight,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     armLeft,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     plow,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     twirler,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    test,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	bool right = true;

	while(true)
	{
		eraseDisplay();
		if(nNxtButtonPressed == 3)
		{
			if(right)
				right = false;
			else
				right = true;
		}
		if(right)
		{
			nxtDisplayCenteredBigTextLine(3, "RIGHT");
			if(nNxtButtonPressed == 1)
				motor[armRight] = 100;
			else if(nNxtButtonPressed == 2)
				motor[armRight] = -100;
			else
				motor[armRight] = 0;
		}
		else if(!right)
		{
			nxtDisplayCenteredBigTextLine(3, "LEFT");
			if(nNxtButtonPressed == 1)
				motor[armLeft] = 100;
			else if(nNxtButtonPressed == 2)
				motor[armLeft] = -100;
			else
				motor[armLeft] = 0;
		}
	}
}
